support ros2 humble
sbgisen/fdilink_ahrs pull request #13
Opened 2024-02-14 07:23 UTC by Tacha-S

## Summary

ROS2 humbleで動作するようにしました。

- fix 

## Detail

## Impact

## Test

  

## Attention

2024-02-16 10:39 UTC, jsupratman13 requested changes
* dynamic_reconfigure -> parameter_callbackになったよね？それ入れないの？
* launchファイルと cfg必要無いなら消してもいいかも

2024-02-16 10:39 UTC, jsupratman13 commented on launch/ahrs_driver.launch.py
> +        default_value='/dev/ttyUSB1')
USB0にして欲しい

2024-02-19 01:21 UTC, Tacha-S commented
個人的にはこのパラメータを動的に変更すること殆どないと思っていたのでcallbackするまでもないと思っていました。

dynamic_reconfigure にあった機能を残して欲しいというROS1の機能維持と、USB1->USB0にしてほしいという改変両方混在しているんですけどどっちがいいんですか？

2024-02-19 02:16 UTC, Tacha-S commented
dynamic reconfigureのパラメータをそもそもパラメータにし忘れていたのでパラメータ化したついでに、動的変更にも対応させておきました。

2024-02-19 02:16 UTC, Tacha-S commented on launch/ahrs_driver.launch.py
> +        default_value='/dev/ttyUSB1')
ROS1でもUSB1なので、USB0にするのは構わないですけどROS1の方にもPR出しておいてくれますか？

2024-02-19 03:16 UTC, jsupratman13 commented on launch/ahrs_driver.launch.py
> +        default_value='/dev/ttyUSB1')
:bow: ごめんROS1がUSB1だったこと忘れていました．このままで大丈夫です．

2024-02-19 05:10 UTC, jsupratman13 reviewed
動作確認しておきます．

2024-09-18 05:09 UTC, Tacha-S commented
@jsupratman13 ping

2024-09-18 05:33 UTC, jsupratman13 commented
ごめん，すでに動作確認してapprove・merge忘れていました．

2024-09-18 05:33 UTC, jsupratman13 approved these changes

2024-09-18 05:34 UTC, merged