Convert mG to T
sbgisen/fdilink_ahrs pull request #9
Opened 2022-12-27 08:46 UTC by Tacha-S

## Summary

- fix #8 

## Detail

## Impact

## Test

  

## Attention

2022-12-27 09:44 UTC, nyxrobotics requested changes
単位はOKです。磁石近づけて試してみたのですが、x~とz~の正負が逆のようです。確認お願いします。
→xのみ逆でした

2022-12-28 02:43 UTC, jsupratman13 commented
[商品ページ](https://ja.aliexpress.com/item/1005002521917600.html?spm=a2g0o.order_list.0.0.21ef585am7Cfhi&gatewayAdapt=glo2jpn)からだと単位は μT だと思いましたが違いますか？

2022-12-28 03:15 UTC, Tacha-S commented
見落としてるかもしれませんが、測定誤差の単位と同じだという主張よりは、ソースコードのコメントにある単位のほうが信憑性高くないですか？
センサー値見た感じもmGだと思います。(スケールとしては1桁あがるだけで地磁気からペースメーカーになるようですしhttps://en.wikipedia.org/wiki/Orders_of_magnitude_(magnetic_field))

2022-12-28 03:37 UTC, jsupratman13 commented
> 単位はOKです。磁石近づけて試してみたのですが、xとzの正負が逆のようです。確認お願いします。

磁石で近づけて試してみました．
xの正負が正しく，y,zの正負が逆になっていると思います．

2022-12-28 03:55 UTC, Tacha-S commented
xの符号だけ反転させました

2022-12-28 04:01 UTC, jsupratman13 approved these changes

2022-12-28 04:01 UTC, merged